### ISSUE TITLE
Warning i informacja dla usera - o tym samym w różnych językach

### ISSUE THREAD

**Issue by boczkas** [Hoymm/XO#22]
May 10, 2018 9:09:45 AM GameState.UserIO.InputParams insertAndValidatePlayerName
WARNING: User tried to insert empty name
Imię powinno zawierać jedynie litery. "" jest nieakceptowalne.
Wprowadź imię gracza dla symbolu O :

**Comment by Hoymm** [comment]
Łyka wszystko bez restrykcji
