### ISSUE TITLE
Wpisanie znaku ze spacjami nie jest uważane za dobry wpis

### ISSUE THREAD

**Issue by boczkas** [Hoymm/XO#25]
Proszę wprowadź O (duże o) lub X (duży x), żaden inny symbol nie będzie akceptowany.
Kto powinien zaczynać pierwszy? Wpisz symbol gracza ([O] or [X]): 
      O     
Proszę wprowadź O (duże o) lub X (duży x), żaden inny symbol nie będzie akceptowany.
Kto powinien zaczynać pierwszy? Wpisz symbol gracza ([O] or [X]):

**Comment by Hoymm** [comment]
Naprawione
